### ISSUE TITLE
Error running in the web

### ISSUE THREAD

**Issue by GustavoBonfimS** [SohelIslamImran/expo-in-app-updates#1]
I would like to try this package in my app, but I faced some issues when running the web version.

First, I tried to conditionally return if the app was running on the web, but I received some native module errors. The only way I got this working was by creating a file with a .web.ts extension and exporting the useInAppUpdates hook as an empty function.

However, it would be nice to have this handled internally within the library to make it work properly on the web.

What do you think about this? I'd be happy to help with it.

**Comment by SohelIslamImran** [comment]
Thank you so much for trying it out. I will add web support in some hours.

**Comment by SohelIslamImran** [comment]
Published new version. Please check and let me know!

**Comment by GustavoBonfimS** [comment]
Hi, today I tried version 0.1.2 on the web and got the following error:

<img width="1464" alt="image" src="https://github.com/user-attachments/assets/c1c9bf47-6b0d-44b2-9a0a-8952847b0c90">

**Comment by SohelIslamImran** [comment]
Strange... Can you open your `node_module/expo-in-app-updates/build` and give me a screenshot? @GustavoBonfimS

**Comment by SohelIslamImran** [comment]
You can try to delete your `node_module` and reinstall the latest version and then let me know

**Comment by GustavoBonfimS** [comment]
> Strange... Can you open your `node_module/expo-in-app-updates/build` and give me a screenshot? @GustavoBonfimS

<img width="1136" alt="image" src="https://github.com/user-attachments/assets/e7d5aa8a-0c2a-4cdc-994d-b68303f45b21">

**Comment by SohelIslamImran** [comment]
After installing, did you clear your metro? `npx expo run --web --clear` @GustavoBonfimS .. Please let me know

**Comment by SohelIslamImran** [comment]
OK, I found what can be the cause for the issue.. Fixing...

**Comment by GustavoBonfimS** [comment]
I suggest updating the README to include a web platform check and return, like this:
`if (__DEV__ || Platform.OS === 'web') return;`

This will help users understand that this library has no effect on the web platform.

**Comment by SohelIslamImran** [comment]
@GustavoBonfimS I just published a new version, which should fix it. Can you please check now?

**Comment by GustavoBonfimS** [comment]
It's working fine now, nice job!

**Comment by SohelIslamImran** [comment]
Thank you so much for trying the library.
