### ISSUE TITLE
How to test?

### ISSUE THREAD

**Issue by frozencap** [SohelIslamImran/expo-in-app-updates#5]
long shot but,

any way perhaps to test this before shipping to prod?

congrats on the great library launch btw!

**Comment by SohelIslamImran** [comment]
Here is an official guide for [Testing in-app updates](https://developer.android.com/guide/playcore/in-app-updates/test) on Android

**Comment by SohelIslamImran** [comment]
https://stackoverflow.com/a/59456561

**Comment by hems** [comment]
@SohelIslamImran any recommendation / suggesiton on how to test on iOS ?

**Comment by SohelIslamImran** [comment]
@hems 
### Testing In-App Updates

### Android

Use [internal app sharing](https://support.google.com/googleplay/android-developer/answer/9844679) of Play Console to [**Test in-app updates**](https://developer.android.com/guide/playcore/in-app-updates/test)

#### iOS

To test in-app updates on iOS:

1. First publish your app to App Store at least once. Then make sure you have set the correct `AppStoreID` in your `app.json` / `app.config.js`.
2. Create a Development/Production/TestFlight build with a lower version number than your App Store version
3. Install the build on your device
4. Run the app and the update check should detect the newer App Store version

> **Note:** The iTunes Search API used for version checking may have some delay in reflecting the latest App Store version. It's recommended to wait a few minutes after publishing a new version before testing.

**Comment by hems** [comment]
thank you @SohelIslamImran !

**Comment by RafaelCENG** [comment]
Hi thanks for the amazing library. I tested both methods. Emergency and optional update both working. 
checkUpdate
```js
import { compare } from "compare-versions"
import * as ExpoInAppUpdates from "expo-in-app-updates"
import { Alert, Platform } from "react-native"
export const checkInAppUpdate = async (
  minimumVersionAllowed: string,
  setShowDialog: (value: boolean) => void,
  setShowLogin: (value: boolean) => void,
) => {
  if (__DEV__ || Platform.OS === "web") return
  try {
    const { updateAvailable, storeVersion } =
      await ExpoInAppUpdates.checkForUpdate()

    if (!updateAvailable) return

    if (compare(storeVersion, minimumVersionAllowed, "<")) {
      setShowDialog(true)
      setShowLogin(true)
      return
    }

    if (Platform.OS === "android") {
      await ExpoInAppUpdates.startUpdate()
    } else {
      Alert.alert(
        "Update available",
        "A new version of the app is available with many improvements and bug fixes. Would you like to update now?",
        [
          { text: "Cancel", style: "cancel" },
          {
            text: "Update",
            isPreferred: true,
            async onPress() {
              await ExpoInAppUpdates.startUpdate()
            },
          },
        ],
      )
    }
  } catch (error) {
    console.error("In-app update check failed:", error)
  }
}
```
index.ts
```js
  const [showDialog, setShowDialog] = useState(false)
  const [showLogin, setShowLogin] = useState(false)
  const completedUnsubscribe = ExpoInAppUpdates.addUpdateListener(
    "updateCompleted",
    () => {
      setShowDialog(false)
    },
  )

  useEffect(() => {
    const runAppLogic = async () => {
      if (versionPending) return

      if (version) {
        await checkInAppUpdate(version, setShowDialog, setShowLogin)
      }

      if (userState === "anon" || showLogin === true) {
        if (router.canDismiss()) router.dismissAll()
        router.replace("/login")
      SplashScreen.hideAsync()
    }

    runAppLogic()
    // Cleanup
    return () => {
      completedUnsubscribe()
    }
  }, [versionPending, version, userState, showLogin])
```
Small part of my code might help someone!

**Comment by SohelIslamImran** [comment]
Thank you! So you tested the `v10.0-beta.0` and the `addUpdateListener`, and it's working fine? Sounds good.. So, should I publish this change as a stable version?

**Comment by RafaelCENG** [comment]
Yes it worked for me. Would be nice to have a 2nd opinion also.
