### ISSUE TITLE
App Store takes some time to update the version on `lookup` or caching issue

### ISSUE THREAD

**Issue by efstathiosntonas** [SohelIslamImran/expo-in-app-updates#6]
It seems that iOS `https://itunes.apple.com/lookup?id=XXXXX` needs some time to update to the latest version or something is caching the result. 

I've just released a new version on App Store and the moment I've downloaded the `updateAvailable` was true, the `storeVersion` reported is the previous version of the app. 

The weird part is that if I enter `https://itunes.apple.com/lookup?id=<APP_ID>`  on the browser the json file has the correct version string but for some reason the app fetches an outdated lookup? 

I think we can take advantage of `"currentVersionReleaseDate": "2024-11-01T14:17:55Z"` from the lookup response and only trigger the update 1 day after the release from the react-native hook. 

Will keep deleting the app and reinstalling during the day and see if the alert will stop show up -> the lookup is finally updated.

**Comment by efstathiosntonas** [comment]
One fast solution would be:

```
let timestamp = Date().timeIntervalSince1970
let appStoreURL = URL(string: "https://itunes.apple.com/lookup?id=\(appId)&_=\(timestamp)")!
```

so it skips any cache, just tested it and it fetches the proper version.

**Comment by SohelIslamImran** [comment]
Great! I also faced this issue.. And I was planning to look at it.
